[dependencies]
chrono = "0.4.41"
quick-xml = {version = "0.37", features = ["serialize"]}
thiserror = "2.0.12"
urlencoding = "2.1.3"

[package]
name = "calibre-opf-parser"
version = "0.1.0"
edition = "2024"

[profile.release]
codegen-units = 1
lto = "fat"
